// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Option = require("@rescript/core/src/Core__Option.res.js");

var new_age = 1.1 + 23;

console.log(new_age);

var new_age$1 = "gita" + 23;

console.log(new_age$1);

var y = {
  contents: 5
};

y.contents = y.contents + 1 | 0;

var message = "hello gitanjli";

console.log("hello " + message);

console.log("Hello");

console.log("gitanjli");

console.log("equal");

var myResult = {
  TAG: "Success",
  _0: "I did it!"
};

if (myResult.TAG === "Success") {
  console.log("I did it!");
} else {
  console.log("Failure: I did it!");
}

function myFunction(input) {
  if (input === "valid") {
    return {
            TAG: "Success",
            _0: "Operation success"
          };
  } else {
    return {
            TAG: "Failure",
            _0: "Operation error"
          };
  }
}

var result = myFunction("valid");

if (result.TAG === "Success") {
  console.log("Success: " + result._0);
} else {
  console.log("from this switch statement");
  console.log("Faliure: " + result._0);
}

var g = {
  contents: "gitanjli"
};

g.contents = g.contents + "chopra";

console.log(g);

function convertBoolToString(val) {
  if (val) {
    return "true";
  } else {
    return "false";
  }
}

console.log(true);

console.log("status above");

console.log("true++ status");

console.log("true");

console.log();

var point1 = {
  x: 35,
  y: 40
};

point1.y = 90;

console.log(point1.x);

console.log(point1.y);

var point2 = {
  x: 60,
  y: point1.y
};

console.log(point2.x);

console.log(point2.y);

var arrayA = [
  1,
  2,
  3,
  4
];

console.log(Core__Option.getOr(arrayA[0], 0).toString() + " 0th item array");

console.log("hey, this is gitanjli, i am " + (23).toString() + " years old");

for(var i = 0; i <= 10; ++i){
  console.log(i);
}

for(var i$1 = 10; i$1 >= 0; --i$1){
  console.log(i$1);
}

var val = {
  contents: true
};

while(val.contents === true) {
  console.log("true");
  val.contents = false;
};

console.log("hello");

console.log(1);

var A = {
  b: 4
};

var B = {
  b: 5
};

function add(a, b) {
  return 5 + b | 0;
}

function drawCircle(r) {
  return "perfect circle";
}

var student1 = {
  name: "Gitanjli",
  age: 23
};

var age = 23;

var status;

var abc = 1;

var x = 23;

var position = [
  1,
  2,
  2
];

var a = [
  1,
  2,
  2
];

var b = [
  "top",
  "right",
  "up"
];

exports.new_age = new_age$1;
exports.y = y;
exports.message = message;
exports.student1 = student1;
exports.age = age;
exports.myResult = myResult;
exports.myFunction = myFunction;
exports.result = result;
exports.g = g;
exports.convertBoolToString = convertBoolToString;
exports.status = status;
exports.point1 = point1;
exports.point2 = point2;
exports.arrayA = arrayA;
exports.val = val;
exports.abc = abc;
exports.A = A;
exports.B = B;
exports.add = add;
exports.drawCircle = drawCircle;
exports.x = x;
exports.position = position;
exports.a = a;
exports.b = b;
/*  Not a pure module */
