// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Option = require("@rescript/core/src/Core__Option.res.js");

var new_age = 1.1 + 23;

console.log(new_age);

var new_age$1 = "gita" + 23;

console.log(new_age$1);

var y = {
  contents: 5
};

y.contents = y.contents + 1 | 0;

var message = "hello gitanjli";

console.log("hello " + message);

console.log("Hello");

console.log("gitanjli");

console.log("equal");

var myResult = {
  TAG: "Success",
  _0: "I did it!"
};

if (myResult.TAG === "Success") {
  console.log("I did it!");
} else {
  console.log("Failure: I did it!");
}

function myFunction(input) {
  if (input === "valid") {
    return {
            TAG: "Success",
            _0: "Operation success"
          };
  } else {
    return {
            TAG: "Failure",
            _0: "Operation error"
          };
  }
}

var result = myFunction("valid");

if (result.TAG === "Success") {
  console.log("Success: " + result._0);
} else {
  console.log("from this switch statement");
  console.log("Faliure: " + result._0);
}

var g = {
  contents: "gitanjli"
};

g.contents = g.contents + "chopra";

console.log(g);

console.log("true");

var point1 = {
  x: 35,
  y: 40
};

point1.y = 90;

console.log(point1.x);

console.log(point1.y);

var point2 = {
  x: 60,
  y: point1.y
};

console.log(point2.x);

console.log(point2.y);

var arrayA = [
  1,
  2,
  3,
  4
];

console.log(Core__Option.getOr(arrayA[0], 0).toString() + " 0th item array");

var x = 5;

var student1 = {
  name: "Gitanjli",
  age: 23
};

var age = 23;

exports.new_age = new_age$1;
exports.x = x;
exports.y = y;
exports.message = message;
exports.student1 = student1;
exports.age = age;
exports.myResult = myResult;
exports.myFunction = myFunction;
exports.result = result;
exports.g = g;
exports.point1 = point1;
exports.point2 = point2;
exports.arrayA = arrayA;
/*  Not a pure module */
