// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var new_age = 1.1 + 23;

console.log(new_age);

var y = {
  contents: 5
};

y.contents = y.contents + 1 | 0;

var message = "gitanjli";

console.log("hello " + message);

console.log("Hello");

console.log("gitanjli");

console.log("equal");

console.log(7);

var x = 5;

var student1 = {
  name: "Gitanjli",
  age: 23
};

var age = 23;

var sum = 7;

exports.new_age = new_age;
exports.x = x;
exports.y = y;
exports.message = message;
exports.student1 = student1;
exports.age = age;
exports.sum = sum;
/*  Not a pure module */
