// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MyJsFileJs = require("./MyJsFile.js");

var me = {
  age: "23"
};

var mei = {
  age: "23"
};

var age = mei.age;

var student1 = MyJsFileJs.student1;

console.log(student1);

var mypoint = {
  x: 3.3,
  y: 2.4,
  z: 4.22
};

console.log(mypoint);

var A = {
  me: me,
  mei: mei,
  age: age,
  student1: student1,
  mypoint: mypoint
};

exports.A = A;
/* age Not a pure module */
