// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var me = {
  age: "23"
};

var mei = {
  age: "23"
};

var age = mei.age;

var mypoint = {
  x: 3.3,
  y: 2.4,
  z: 4.22
};

console.log(mypoint);

var A = {
  me: me,
  mei: mei,
  age: age,
  mypoint: mypoint
};

exports.A = A;
/* age Not a pure module */
