// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var me = {
  age: "23"
};

var mei = {
  age: "23"
};

var age = mei.age;

var A = {
  me: me,
  mei: mei,
  age: age
};

exports.A = A;
/* age Not a pure module */
