// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function render(mycolor) {
  if (mycolor === "yellow") {
    console.log("this is yellow");
  } else if (mycolor === "green" || mycolor === "red") {
    console.log("Hello this is red or green");
  } else {
    console.log("hello blue!");
  }
}

var mycolor = "red";

var mylabel = "aria-hidden";

var mynumber = 7;

var me = {
  NAME: "Instagram",
  VAL: "gitanjli"
};

var my = {
  NAME: "Facebook",
  VAL: [
    "gitu",
    23
  ]
};

exports.mycolor = mycolor;
exports.mylabel = mylabel;
exports.mynumber = mynumber;
exports.render = render;
exports.me = me;
exports.my = my;
/* No side effect */
