// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function nameFromB(b) {
  return b.name;
}

var name = "gitu";

console.log(name);

var A_a = {
  id: "1",
  name: "gitu",
  age: 35,
  working: true
};

var A = {
  nameFromB: nameFromB,
  a: A_a,
  name: name
};

exports.A = A;
/*  Not a pure module */
