// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function nameFromB(b) {
  return b.name;
}

var name = "gitu";

console.log(name);

var A_a = {
  id: "1",
  name: "gitu",
  age: 35,
  working: true
};

var A = {
  nameFromB: nameFromB,
  a: A_a,
  name: name
};

function nameFromD(d) {
  return d.name;
}

var B_c = {
  name: "gitanjli",
  age: 23
};

var B = {
  nameFromD: nameFromD,
  c: B_c
};

exports.A = A;
exports.B = B;
/*  Not a pure module */
