// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Unboxedd_studentname = {
  TAG: "Name",
  _0: "gitanjli"
};

var Unboxedd_hi = {
  message: "hello!"
};

var Unboxedd = {
  studentname: Unboxedd_studentname,
  hi: Unboxedd_hi
};

var myArray = [
  "Hello",
  true,
  false,
  13.222
];

var Unboxedd_clean = {
  studentName: "gitanjli",
  hi: "hello!",
  myArray: myArray
};

var fine = "Yes";

var pet = "Dog";

var pet2 = "Cat";

var myAccount = {
  TAG: "Instagram",
  _0: "gitanjli"
};

var me = {
  TAG: "Id",
  name: "Joe",
  password: "124343"
};

var ram = "Human";

exports.fine = fine;
exports.pet = pet;
exports.pet2 = pet2;
exports.myAccount = myAccount;
exports.me = me;
exports.ram = ram;
exports.Unboxedd = Unboxedd;
exports.Unboxedd_clean = Unboxedd_clean;
/* No side effect */
